import { index_a } from './src/index_a';
import { index_b } from './src/index_b';
import { index_c } from './src/index_c';
import { index_d } from './src/index_d';
import { index_e } from './src/index_e';
import { index_f } from './src/index_f';
import { index_g } from './src/index_g';
import { index_h } from './src/index_h';
import { index_i } from './src/index_i';
import { index_j } from './src/index_j';
import { index_k } from './src/index_k';
import { index_l } from './src/index_l';
import { index_m } from './src/index_m';
import { index_n } from './src/index_n';
import { index_o } from './src/index_o';
import { index_p } from './src/index_p';
import { index_q } from './src/index_q';
import { index_r } from './src/index_r';
import { index_s } from './src/index_s';
import { index_t } from './src/index_t';
import { index_u } from './src/index_u';
import { index_v } from './src/index_v';
import { index_w } from './src/index_w';
import { index_x } from './src/index_x';
import { index_y } from './src/index_y';
import { index_z } from './src/index_z';

export function run () {
   index_a();
   index_b();
   index_c();
   index_d();
   index_e();
   index_f();
   index_g();
   index_h();
   index_i();
   index_j();
   index_k();
   index_l();
   index_m();
   index_n();
   index_o();
   index_p();
   index_q();
   index_r();
   index_s();
   index_t();
   index_u();
   index_v();
   index_w();
   index_x();
   index_y();
   index_z();
}
