import { index_c_a } from './index_c/index_c_a';
import { index_c_b } from './index_c/index_c_b';
import { index_c_c } from './index_c/index_c_c';
import { index_c_d } from './index_c/index_c_d';
import { index_c_e } from './index_c/index_c_e';
import { index_c_f } from './index_c/index_c_f';
import { index_c_g } from './index_c/index_c_g';
import { index_c_h } from './index_c/index_c_h';
import { index_c_i } from './index_c/index_c_i';
import { index_c_j } from './index_c/index_c_j';
import { index_c_k } from './index_c/index_c_k';
import { index_c_l } from './index_c/index_c_l';
import { index_c_m } from './index_c/index_c_m';
import { index_c_n } from './index_c/index_c_n';
import { index_c_o } from './index_c/index_c_o';
import { index_c_p } from './index_c/index_c_p';
import { index_c_q } from './index_c/index_c_q';
import { index_c_r } from './index_c/index_c_r';
import { index_c_s } from './index_c/index_c_s';
import { index_c_t } from './index_c/index_c_t';
import { index_c_u } from './index_c/index_c_u';
import { index_c_v } from './index_c/index_c_v';
import { index_c_w } from './index_c/index_c_w';
import { index_c_x } from './index_c/index_c_x';
import { index_c_y } from './index_c/index_c_y';
import { index_c_z } from './index_c/index_c_z';
export function index_c() {
    index_c_a();
    index_c_b();
    index_c_c();
    index_c_d();
    index_c_e();
    index_c_f();
    index_c_g();
    index_c_h();
    index_c_i();
    index_c_j();
    index_c_k();
    index_c_l();
    index_c_m();
    index_c_n();
    index_c_o();
    index_c_p();
    index_c_q();
    index_c_r();
    index_c_s();
    index_c_t();
    index_c_u();
    index_c_v();
    index_c_w();
    index_c_x();
    index_c_y();
    index_c_z();
}
            