import { index_g_a } from './index_g/index_g_a';
import { index_g_b } from './index_g/index_g_b';
import { index_g_c } from './index_g/index_g_c';
import { index_g_d } from './index_g/index_g_d';
import { index_g_e } from './index_g/index_g_e';
import { index_g_f } from './index_g/index_g_f';
import { index_g_g } from './index_g/index_g_g';
import { index_g_h } from './index_g/index_g_h';
import { index_g_i } from './index_g/index_g_i';
import { index_g_j } from './index_g/index_g_j';
import { index_g_k } from './index_g/index_g_k';
import { index_g_l } from './index_g/index_g_l';
import { index_g_m } from './index_g/index_g_m';
import { index_g_n } from './index_g/index_g_n';
import { index_g_o } from './index_g/index_g_o';
import { index_g_p } from './index_g/index_g_p';
import { index_g_q } from './index_g/index_g_q';
import { index_g_r } from './index_g/index_g_r';
import { index_g_s } from './index_g/index_g_s';
import { index_g_t } from './index_g/index_g_t';
import { index_g_u } from './index_g/index_g_u';
import { index_g_v } from './index_g/index_g_v';
import { index_g_w } from './index_g/index_g_w';
import { index_g_x } from './index_g/index_g_x';
import { index_g_y } from './index_g/index_g_y';
import { index_g_z } from './index_g/index_g_z';
export function index_g() {
    index_g_a();
    index_g_b();
    index_g_c();
    index_g_d();
    index_g_e();
    index_g_f();
    index_g_g();
    index_g_h();
    index_g_i();
    index_g_j();
    index_g_k();
    index_g_l();
    index_g_m();
    index_g_n();
    index_g_o();
    index_g_p();
    index_g_q();
    index_g_r();
    index_g_s();
    index_g_t();
    index_g_u();
    index_g_v();
    index_g_w();
    index_g_x();
    index_g_y();
    index_g_z();
}
            