import { index_s_a } from './src/index_s/index_s_a';
import { index_s_b } from './src/index_s/index_s_b';
import { index_s_c } from './src/index_s/index_s_c';
import { index_s_d } from './src/index_s/index_s_d';
import { index_s_e } from './src/index_s/index_s_e';
import { index_s_f } from './src/index_s/index_s_f';
import { index_s_g } from './src/index_s/index_s_g';
import { index_s_h } from './src/index_s/index_s_h';
import { index_s_i } from './src/index_s/index_s_i';
import { index_s_j } from './src/index_s/index_s_j';
import { index_s_k } from './src/index_s/index_s_k';
import { index_s_l } from './src/index_s/index_s_l';
import { index_s_m } from './src/index_s/index_s_m';
import { index_s_n } from './src/index_s/index_s_n';
import { index_s_o } from './src/index_s/index_s_o';
import { index_s_p } from './src/index_s/index_s_p';
import { index_s_q } from './src/index_s/index_s_q';
import { index_s_r } from './src/index_s/index_s_r';
import { index_s_s } from './src/index_s/index_s_s';
import { index_s_t } from './src/index_s/index_s_t';
import { index_s_u } from './src/index_s/index_s_u';
import { index_s_v } from './src/index_s/index_s_v';
import { index_s_w } from './src/index_s/index_s_w';
import { index_s_x } from './src/index_s/index_s_x';
import { index_s_y } from './src/index_s/index_s_y';
import { index_s_z } from './src/index_s/index_s_z';
export function index_s() {
    index_s_a();
    index_s_b();
    index_s_c();
    index_s_d();
    index_s_e();
    index_s_f();
    index_s_g();
    index_s_h();
    index_s_i();
    index_s_j();
    index_s_k();
    index_s_l();
    index_s_m();
    index_s_n();
    index_s_o();
    index_s_p();
    index_s_q();
    index_s_r();
    index_s_s();
    index_s_t();
    index_s_u();
    index_s_v();
    index_s_w();
    index_s_x();
    index_s_y();
    index_s_z();
}
            