import { index_t_a } from './index_t/index_t_a';
import { index_t_b } from './index_t/index_t_b';
import { index_t_c } from './index_t/index_t_c';
import { index_t_d } from './index_t/index_t_d';
import { index_t_e } from './index_t/index_t_e';
import { index_t_f } from './index_t/index_t_f';
import { index_t_g } from './index_t/index_t_g';
import { index_t_h } from './index_t/index_t_h';
import { index_t_i } from './index_t/index_t_i';
import { index_t_j } from './index_t/index_t_j';
import { index_t_k } from './index_t/index_t_k';
import { index_t_l } from './index_t/index_t_l';
import { index_t_m } from './index_t/index_t_m';
import { index_t_n } from './index_t/index_t_n';
import { index_t_o } from './index_t/index_t_o';
import { index_t_p } from './index_t/index_t_p';
import { index_t_q } from './index_t/index_t_q';
import { index_t_r } from './index_t/index_t_r';
import { index_t_s } from './index_t/index_t_s';
import { index_t_t } from './index_t/index_t_t';
import { index_t_u } from './index_t/index_t_u';
import { index_t_v } from './index_t/index_t_v';
import { index_t_w } from './index_t/index_t_w';
import { index_t_x } from './index_t/index_t_x';
import { index_t_y } from './index_t/index_t_y';
import { index_t_z } from './index_t/index_t_z';
export function index_t() {
    index_t_a();
    index_t_b();
    index_t_c();
    index_t_d();
    index_t_e();
    index_t_f();
    index_t_g();
    index_t_h();
    index_t_i();
    index_t_j();
    index_t_k();
    index_t_l();
    index_t_m();
    index_t_n();
    index_t_o();
    index_t_p();
    index_t_q();
    index_t_r();
    index_t_s();
    index_t_t();
    index_t_u();
    index_t_v();
    index_t_w();
    index_t_x();
    index_t_y();
    index_t_z();
}
            