import { index_a_a } from './src/index_a/index_a_a';
import { index_a_b } from './src/index_a/index_a_b';
import { index_a_c } from './src/index_a/index_a_c';
import { index_a_d } from './src/index_a/index_a_d';
import { index_a_e } from './src/index_a/index_a_e';
import { index_a_f } from './src/index_a/index_a_f';
import { index_a_g } from './src/index_a/index_a_g';
import { index_a_h } from './src/index_a/index_a_h';
import { index_a_i } from './src/index_a/index_a_i';
import { index_a_j } from './src/index_a/index_a_j';
import { index_a_k } from './src/index_a/index_a_k';
import { index_a_l } from './src/index_a/index_a_l';
import { index_a_m } from './src/index_a/index_a_m';
import { index_a_n } from './src/index_a/index_a_n';
import { index_a_o } from './src/index_a/index_a_o';
import { index_a_p } from './src/index_a/index_a_p';
import { index_a_q } from './src/index_a/index_a_q';
import { index_a_r } from './src/index_a/index_a_r';
import { index_a_s } from './src/index_a/index_a_s';
import { index_a_t } from './src/index_a/index_a_t';
import { index_a_u } from './src/index_a/index_a_u';
import { index_a_v } from './src/index_a/index_a_v';
import { index_a_w } from './src/index_a/index_a_w';
import { index_a_x } from './src/index_a/index_a_x';
import { index_a_y } from './src/index_a/index_a_y';
import { index_a_z } from './src/index_a/index_a_z';
export function index_a() {
    index_a_a();
    index_a_b();
    index_a_c();
    index_a_d();
    index_a_e();
    index_a_f();
    index_a_g();
    index_a_h();
    index_a_i();
    index_a_j();
    index_a_k();
    index_a_l();
    index_a_m();
    index_a_n();
    index_a_o();
    index_a_p();
    index_a_q();
    index_a_r();
    index_a_s();
    index_a_t();
    index_a_u();
    index_a_v();
    index_a_w();
    index_a_x();
    index_a_y();
    index_a_z();
}
            