import { index_b_a } from './index_b/index_b_a';
import { index_b_b } from './index_b/index_b_b';
import { index_b_c } from './index_b/index_b_c';
import { index_b_d } from './index_b/index_b_d';
import { index_b_e } from './index_b/index_b_e';
import { index_b_f } from './index_b/index_b_f';
import { index_b_g } from './index_b/index_b_g';
import { index_b_h } from './index_b/index_b_h';
import { index_b_i } from './index_b/index_b_i';
import { index_b_j } from './index_b/index_b_j';
import { index_b_k } from './index_b/index_b_k';
import { index_b_l } from './index_b/index_b_l';
import { index_b_m } from './index_b/index_b_m';
import { index_b_n } from './index_b/index_b_n';
import { index_b_o } from './index_b/index_b_o';
import { index_b_p } from './index_b/index_b_p';
import { index_b_q } from './index_b/index_b_q';
import { index_b_r } from './index_b/index_b_r';
import { index_b_s } from './index_b/index_b_s';
import { index_b_t } from './index_b/index_b_t';
import { index_b_u } from './index_b/index_b_u';
import { index_b_v } from './index_b/index_b_v';
import { index_b_w } from './index_b/index_b_w';
import { index_b_x } from './index_b/index_b_x';
import { index_b_y } from './index_b/index_b_y';
import { index_b_z } from './index_b/index_b_z';
export function index_b() {
    index_b_a();
    index_b_b();
    index_b_c();
    index_b_d();
    index_b_e();
    index_b_f();
    index_b_g();
    index_b_h();
    index_b_i();
    index_b_j();
    index_b_k();
    index_b_l();
    index_b_m();
    index_b_n();
    index_b_o();
    index_b_p();
    index_b_q();
    index_b_r();
    index_b_s();
    index_b_t();
    index_b_u();
    index_b_v();
    index_b_w();
    index_b_x();
    index_b_y();
    index_b_z();
}
            