import { index_f_a } from './index_f/index_f_a';
import { index_f_b } from './index_f/index_f_b';
import { index_f_c } from './index_f/index_f_c';
import { index_f_d } from './index_f/index_f_d';
import { index_f_e } from './index_f/index_f_e';
import { index_f_f } from './index_f/index_f_f';
import { index_f_g } from './index_f/index_f_g';
import { index_f_h } from './index_f/index_f_h';
import { index_f_i } from './index_f/index_f_i';
import { index_f_j } from './index_f/index_f_j';
import { index_f_k } from './index_f/index_f_k';
import { index_f_l } from './index_f/index_f_l';
import { index_f_m } from './index_f/index_f_m';
import { index_f_n } from './index_f/index_f_n';
import { index_f_o } from './index_f/index_f_o';
import { index_f_p } from './index_f/index_f_p';
import { index_f_q } from './index_f/index_f_q';
import { index_f_r } from './index_f/index_f_r';
import { index_f_s } from './index_f/index_f_s';
import { index_f_t } from './index_f/index_f_t';
import { index_f_u } from './index_f/index_f_u';
import { index_f_v } from './index_f/index_f_v';
import { index_f_w } from './index_f/index_f_w';
import { index_f_x } from './index_f/index_f_x';
import { index_f_y } from './index_f/index_f_y';
import { index_f_z } from './index_f/index_f_z';
export function index_f() {
    index_f_a();
    index_f_b();
    index_f_c();
    index_f_d();
    index_f_e();
    index_f_f();
    index_f_g();
    index_f_h();
    index_f_i();
    index_f_j();
    index_f_k();
    index_f_l();
    index_f_m();
    index_f_n();
    index_f_o();
    index_f_p();
    index_f_q();
    index_f_r();
    index_f_s();
    index_f_t();
    index_f_u();
    index_f_v();
    index_f_w();
    index_f_x();
    index_f_y();
    index_f_z();
}
            