import { index_m_a } from './src/index_m/index_m_a';
import { index_m_b } from './src/index_m/index_m_b';
import { index_m_c } from './src/index_m/index_m_c';
import { index_m_d } from './src/index_m/index_m_d';
import { index_m_e } from './src/index_m/index_m_e';
import { index_m_f } from './src/index_m/index_m_f';
import { index_m_g } from './src/index_m/index_m_g';
import { index_m_h } from './src/index_m/index_m_h';
import { index_m_i } from './src/index_m/index_m_i';
import { index_m_j } from './src/index_m/index_m_j';
import { index_m_k } from './src/index_m/index_m_k';
import { index_m_l } from './src/index_m/index_m_l';
import { index_m_m } from './src/index_m/index_m_m';
import { index_m_n } from './src/index_m/index_m_n';
import { index_m_o } from './src/index_m/index_m_o';
import { index_m_p } from './src/index_m/index_m_p';
import { index_m_q } from './src/index_m/index_m_q';
import { index_m_r } from './src/index_m/index_m_r';
import { index_m_s } from './src/index_m/index_m_s';
import { index_m_t } from './src/index_m/index_m_t';
import { index_m_u } from './src/index_m/index_m_u';
import { index_m_v } from './src/index_m/index_m_v';
import { index_m_w } from './src/index_m/index_m_w';
import { index_m_x } from './src/index_m/index_m_x';
import { index_m_y } from './src/index_m/index_m_y';
import { index_m_z } from './src/index_m/index_m_z';
export function index_m() {
    index_m_a();
    index_m_b();
    index_m_c();
    index_m_d();
    index_m_e();
    index_m_f();
    index_m_g();
    index_m_h();
    index_m_i();
    index_m_j();
    index_m_k();
    index_m_l();
    index_m_m();
    index_m_n();
    index_m_o();
    index_m_p();
    index_m_q();
    index_m_r();
    index_m_s();
    index_m_t();
    index_m_u();
    index_m_v();
    index_m_w();
    index_m_x();
    index_m_y();
    index_m_z();
}
            