import { index_v_a } from './index_v/index_v_a';
import { index_v_b } from './index_v/index_v_b';
import { index_v_c } from './index_v/index_v_c';
import { index_v_d } from './index_v/index_v_d';
import { index_v_e } from './index_v/index_v_e';
import { index_v_f } from './index_v/index_v_f';
import { index_v_g } from './index_v/index_v_g';
import { index_v_h } from './index_v/index_v_h';
import { index_v_i } from './index_v/index_v_i';
import { index_v_j } from './index_v/index_v_j';
import { index_v_k } from './index_v/index_v_k';
import { index_v_l } from './index_v/index_v_l';
import { index_v_m } from './index_v/index_v_m';
import { index_v_n } from './index_v/index_v_n';
import { index_v_o } from './index_v/index_v_o';
import { index_v_p } from './index_v/index_v_p';
import { index_v_q } from './index_v/index_v_q';
import { index_v_r } from './index_v/index_v_r';
import { index_v_s } from './index_v/index_v_s';
import { index_v_t } from './index_v/index_v_t';
import { index_v_u } from './index_v/index_v_u';
import { index_v_v } from './index_v/index_v_v';
import { index_v_w } from './index_v/index_v_w';
import { index_v_x } from './index_v/index_v_x';
import { index_v_y } from './index_v/index_v_y';
import { index_v_z } from './index_v/index_v_z';
export function index_v() {
    index_v_a();
    index_v_b();
    index_v_c();
    index_v_d();
    index_v_e();
    index_v_f();
    index_v_g();
    index_v_h();
    index_v_i();
    index_v_j();
    index_v_k();
    index_v_l();
    index_v_m();
    index_v_n();
    index_v_o();
    index_v_p();
    index_v_q();
    index_v_r();
    index_v_s();
    index_v_t();
    index_v_u();
    index_v_v();
    index_v_w();
    index_v_x();
    index_v_y();
    index_v_z();
}
            