import { index_u_a } from './index_u/index_u_a';
import { index_u_b } from './index_u/index_u_b';
import { index_u_c } from './index_u/index_u_c';
import { index_u_d } from './index_u/index_u_d';
import { index_u_e } from './index_u/index_u_e';
import { index_u_f } from './index_u/index_u_f';
import { index_u_g } from './index_u/index_u_g';
import { index_u_h } from './index_u/index_u_h';
import { index_u_i } from './index_u/index_u_i';
import { index_u_j } from './index_u/index_u_j';
import { index_u_k } from './index_u/index_u_k';
import { index_u_l } from './index_u/index_u_l';
import { index_u_m } from './index_u/index_u_m';
import { index_u_n } from './index_u/index_u_n';
import { index_u_o } from './index_u/index_u_o';
import { index_u_p } from './index_u/index_u_p';
import { index_u_q } from './index_u/index_u_q';
import { index_u_r } from './index_u/index_u_r';
import { index_u_s } from './index_u/index_u_s';
import { index_u_t } from './index_u/index_u_t';
import { index_u_u } from './index_u/index_u_u';
import { index_u_v } from './index_u/index_u_v';
import { index_u_w } from './index_u/index_u_w';
import { index_u_x } from './index_u/index_u_x';
import { index_u_y } from './index_u/index_u_y';
import { index_u_z } from './index_u/index_u_z';
export function index_u() {
    index_u_a();
    index_u_b();
    index_u_c();
    index_u_d();
    index_u_e();
    index_u_f();
    index_u_g();
    index_u_h();
    index_u_i();
    index_u_j();
    index_u_k();
    index_u_l();
    index_u_m();
    index_u_n();
    index_u_o();
    index_u_p();
    index_u_q();
    index_u_r();
    index_u_s();
    index_u_t();
    index_u_u();
    index_u_v();
    index_u_w();
    index_u_x();
    index_u_y();
    index_u_z();
}
            