import { index_p_a } from './index_p/index_p_a';
import { index_p_b } from './index_p/index_p_b';
import { index_p_c } from './index_p/index_p_c';
import { index_p_d } from './index_p/index_p_d';
import { index_p_e } from './index_p/index_p_e';
import { index_p_f } from './index_p/index_p_f';
import { index_p_g } from './index_p/index_p_g';
import { index_p_h } from './index_p/index_p_h';
import { index_p_i } from './index_p/index_p_i';
import { index_p_j } from './index_p/index_p_j';
import { index_p_k } from './index_p/index_p_k';
import { index_p_l } from './index_p/index_p_l';
import { index_p_m } from './index_p/index_p_m';
import { index_p_n } from './index_p/index_p_n';
import { index_p_o } from './index_p/index_p_o';
import { index_p_p } from './index_p/index_p_p';
import { index_p_q } from './index_p/index_p_q';
import { index_p_r } from './index_p/index_p_r';
import { index_p_s } from './index_p/index_p_s';
import { index_p_t } from './index_p/index_p_t';
import { index_p_u } from './index_p/index_p_u';
import { index_p_v } from './index_p/index_p_v';
import { index_p_w } from './index_p/index_p_w';
import { index_p_x } from './index_p/index_p_x';
import { index_p_y } from './index_p/index_p_y';
import { index_p_z } from './index_p/index_p_z';
export function index_p() {
    index_p_a();
    index_p_b();
    index_p_c();
    index_p_d();
    index_p_e();
    index_p_f();
    index_p_g();
    index_p_h();
    index_p_i();
    index_p_j();
    index_p_k();
    index_p_l();
    index_p_m();
    index_p_n();
    index_p_o();
    index_p_p();
    index_p_q();
    index_p_r();
    index_p_s();
    index_p_t();
    index_p_u();
    index_p_v();
    index_p_w();
    index_p_x();
    index_p_y();
    index_p_z();
}
            