import { index_k_a } from './index_k/index_k_a';
import { index_k_b } from './index_k/index_k_b';
import { index_k_c } from './index_k/index_k_c';
import { index_k_d } from './index_k/index_k_d';
import { index_k_e } from './index_k/index_k_e';
import { index_k_f } from './index_k/index_k_f';
import { index_k_g } from './index_k/index_k_g';
import { index_k_h } from './index_k/index_k_h';
import { index_k_i } from './index_k/index_k_i';
import { index_k_j } from './index_k/index_k_j';
import { index_k_k } from './index_k/index_k_k';
import { index_k_l } from './index_k/index_k_l';
import { index_k_m } from './index_k/index_k_m';
import { index_k_n } from './index_k/index_k_n';
import { index_k_o } from './index_k/index_k_o';
import { index_k_p } from './index_k/index_k_p';
import { index_k_q } from './index_k/index_k_q';
import { index_k_r } from './index_k/index_k_r';
import { index_k_s } from './index_k/index_k_s';
import { index_k_t } from './index_k/index_k_t';
import { index_k_u } from './index_k/index_k_u';
import { index_k_v } from './index_k/index_k_v';
import { index_k_w } from './index_k/index_k_w';
import { index_k_x } from './index_k/index_k_x';
import { index_k_y } from './index_k/index_k_y';
import { index_k_z } from './index_k/index_k_z';
export function index_k() {
    index_k_a();
    index_k_b();
    index_k_c();
    index_k_d();
    index_k_e();
    index_k_f();
    index_k_g();
    index_k_h();
    index_k_i();
    index_k_j();
    index_k_k();
    index_k_l();
    index_k_m();
    index_k_n();
    index_k_o();
    index_k_p();
    index_k_q();
    index_k_r();
    index_k_s();
    index_k_t();
    index_k_u();
    index_k_v();
    index_k_w();
    index_k_x();
    index_k_y();
    index_k_z();
}
            