import { index_l_a } from './src/index_l/index_l_a';
import { index_l_b } from './src/index_l/index_l_b';
import { index_l_c } from './src/index_l/index_l_c';
import { index_l_d } from './src/index_l/index_l_d';
import { index_l_e } from './src/index_l/index_l_e';
import { index_l_f } from './src/index_l/index_l_f';
import { index_l_g } from './src/index_l/index_l_g';
import { index_l_h } from './src/index_l/index_l_h';
import { index_l_i } from './src/index_l/index_l_i';
import { index_l_j } from './src/index_l/index_l_j';
import { index_l_k } from './src/index_l/index_l_k';
import { index_l_l } from './src/index_l/index_l_l';
import { index_l_m } from './src/index_l/index_l_m';
import { index_l_n } from './src/index_l/index_l_n';
import { index_l_o } from './src/index_l/index_l_o';
import { index_l_p } from './src/index_l/index_l_p';
import { index_l_q } from './src/index_l/index_l_q';
import { index_l_r } from './src/index_l/index_l_r';
import { index_l_s } from './src/index_l/index_l_s';
import { index_l_t } from './src/index_l/index_l_t';
import { index_l_u } from './src/index_l/index_l_u';
import { index_l_v } from './src/index_l/index_l_v';
import { index_l_w } from './src/index_l/index_l_w';
import { index_l_x } from './src/index_l/index_l_x';
import { index_l_y } from './src/index_l/index_l_y';
import { index_l_z } from './src/index_l/index_l_z';
export function index_l() {
    index_l_a();
    index_l_b();
    index_l_c();
    index_l_d();
    index_l_e();
    index_l_f();
    index_l_g();
    index_l_h();
    index_l_i();
    index_l_j();
    index_l_k();
    index_l_l();
    index_l_m();
    index_l_n();
    index_l_o();
    index_l_p();
    index_l_q();
    index_l_r();
    index_l_s();
    index_l_t();
    index_l_u();
    index_l_v();
    index_l_w();
    index_l_x();
    index_l_y();
    index_l_z();
}
            