import { index_r_a } from './index_r/index_r_a';
import { index_r_b } from './index_r/index_r_b';
import { index_r_c } from './index_r/index_r_c';
import { index_r_d } from './index_r/index_r_d';
import { index_r_e } from './index_r/index_r_e';
import { index_r_f } from './index_r/index_r_f';
import { index_r_g } from './index_r/index_r_g';
import { index_r_h } from './index_r/index_r_h';
import { index_r_i } from './index_r/index_r_i';
import { index_r_j } from './index_r/index_r_j';
import { index_r_k } from './index_r/index_r_k';
import { index_r_l } from './index_r/index_r_l';
import { index_r_m } from './index_r/index_r_m';
import { index_r_n } from './index_r/index_r_n';
import { index_r_o } from './index_r/index_r_o';
import { index_r_p } from './index_r/index_r_p';
import { index_r_q } from './index_r/index_r_q';
import { index_r_r } from './index_r/index_r_r';
import { index_r_s } from './index_r/index_r_s';
import { index_r_t } from './index_r/index_r_t';
import { index_r_u } from './index_r/index_r_u';
import { index_r_v } from './index_r/index_r_v';
import { index_r_w } from './index_r/index_r_w';
import { index_r_x } from './index_r/index_r_x';
import { index_r_y } from './index_r/index_r_y';
import { index_r_z } from './index_r/index_r_z';
export function index_r() {
    index_r_a();
    index_r_b();
    index_r_c();
    index_r_d();
    index_r_e();
    index_r_f();
    index_r_g();
    index_r_h();
    index_r_i();
    index_r_j();
    index_r_k();
    index_r_l();
    index_r_m();
    index_r_n();
    index_r_o();
    index_r_p();
    index_r_q();
    index_r_r();
    index_r_s();
    index_r_t();
    index_r_u();
    index_r_v();
    index_r_w();
    index_r_x();
    index_r_y();
    index_r_z();
}
            