import { index_y_a } from './src/index_y/index_y_a';
import { index_y_b } from './src/index_y/index_y_b';
import { index_y_c } from './src/index_y/index_y_c';
import { index_y_d } from './src/index_y/index_y_d';
import { index_y_e } from './src/index_y/index_y_e';
import { index_y_f } from './src/index_y/index_y_f';
import { index_y_g } from './src/index_y/index_y_g';
import { index_y_h } from './src/index_y/index_y_h';
import { index_y_i } from './src/index_y/index_y_i';
import { index_y_j } from './src/index_y/index_y_j';
import { index_y_k } from './src/index_y/index_y_k';
import { index_y_l } from './src/index_y/index_y_l';
import { index_y_m } from './src/index_y/index_y_m';
import { index_y_n } from './src/index_y/index_y_n';
import { index_y_o } from './src/index_y/index_y_o';
import { index_y_p } from './src/index_y/index_y_p';
import { index_y_q } from './src/index_y/index_y_q';
import { index_y_r } from './src/index_y/index_y_r';
import { index_y_s } from './src/index_y/index_y_s';
import { index_y_t } from './src/index_y/index_y_t';
import { index_y_u } from './src/index_y/index_y_u';
import { index_y_v } from './src/index_y/index_y_v';
import { index_y_w } from './src/index_y/index_y_w';
import { index_y_x } from './src/index_y/index_y_x';
import { index_y_y } from './src/index_y/index_y_y';
import { index_y_z } from './src/index_y/index_y_z';
export function index_y() {
    index_y_a();
    index_y_b();
    index_y_c();
    index_y_d();
    index_y_e();
    index_y_f();
    index_y_g();
    index_y_h();
    index_y_i();
    index_y_j();
    index_y_k();
    index_y_l();
    index_y_m();
    index_y_n();
    index_y_o();
    index_y_p();
    index_y_q();
    index_y_r();
    index_y_s();
    index_y_t();
    index_y_u();
    index_y_v();
    index_y_w();
    index_y_x();
    index_y_y();
    index_y_z();
}
            