import { index_o_a } from './src/index_o/index_o_a';
import { index_o_b } from './src/index_o/index_o_b';
import { index_o_c } from './src/index_o/index_o_c';
import { index_o_d } from './src/index_o/index_o_d';
import { index_o_e } from './src/index_o/index_o_e';
import { index_o_f } from './src/index_o/index_o_f';
import { index_o_g } from './src/index_o/index_o_g';
import { index_o_h } from './src/index_o/index_o_h';
import { index_o_i } from './src/index_o/index_o_i';
import { index_o_j } from './src/index_o/index_o_j';
import { index_o_k } from './src/index_o/index_o_k';
import { index_o_l } from './src/index_o/index_o_l';
import { index_o_m } from './src/index_o/index_o_m';
import { index_o_n } from './src/index_o/index_o_n';
import { index_o_o } from './src/index_o/index_o_o';
import { index_o_p } from './src/index_o/index_o_p';
import { index_o_q } from './src/index_o/index_o_q';
import { index_o_r } from './src/index_o/index_o_r';
import { index_o_s } from './src/index_o/index_o_s';
import { index_o_t } from './src/index_o/index_o_t';
import { index_o_u } from './src/index_o/index_o_u';
import { index_o_v } from './src/index_o/index_o_v';
import { index_o_w } from './src/index_o/index_o_w';
import { index_o_x } from './src/index_o/index_o_x';
import { index_o_y } from './src/index_o/index_o_y';
import { index_o_z } from './src/index_o/index_o_z';
export function index_o() {
    index_o_a();
    index_o_b();
    index_o_c();
    index_o_d();
    index_o_e();
    index_o_f();
    index_o_g();
    index_o_h();
    index_o_i();
    index_o_j();
    index_o_k();
    index_o_l();
    index_o_m();
    index_o_n();
    index_o_o();
    index_o_p();
    index_o_q();
    index_o_r();
    index_o_s();
    index_o_t();
    index_o_u();
    index_o_v();
    index_o_w();
    index_o_x();
    index_o_y();
    index_o_z();
}
            