import { index_w_a } from './src/index_w/index_w_a';
import { index_w_b } from './src/index_w/index_w_b';
import { index_w_c } from './src/index_w/index_w_c';
import { index_w_d } from './src/index_w/index_w_d';
import { index_w_e } from './src/index_w/index_w_e';
import { index_w_f } from './src/index_w/index_w_f';
import { index_w_g } from './src/index_w/index_w_g';
import { index_w_h } from './src/index_w/index_w_h';
import { index_w_i } from './src/index_w/index_w_i';
import { index_w_j } from './src/index_w/index_w_j';
import { index_w_k } from './src/index_w/index_w_k';
import { index_w_l } from './src/index_w/index_w_l';
import { index_w_m } from './src/index_w/index_w_m';
import { index_w_n } from './src/index_w/index_w_n';
import { index_w_o } from './src/index_w/index_w_o';
import { index_w_p } from './src/index_w/index_w_p';
import { index_w_q } from './src/index_w/index_w_q';
import { index_w_r } from './src/index_w/index_w_r';
import { index_w_s } from './src/index_w/index_w_s';
import { index_w_t } from './src/index_w/index_w_t';
import { index_w_u } from './src/index_w/index_w_u';
import { index_w_v } from './src/index_w/index_w_v';
import { index_w_w } from './src/index_w/index_w_w';
import { index_w_x } from './src/index_w/index_w_x';
import { index_w_y } from './src/index_w/index_w_y';
import { index_w_z } from './src/index_w/index_w_z';
export function index_w() {
    index_w_a();
    index_w_b();
    index_w_c();
    index_w_d();
    index_w_e();
    index_w_f();
    index_w_g();
    index_w_h();
    index_w_i();
    index_w_j();
    index_w_k();
    index_w_l();
    index_w_m();
    index_w_n();
    index_w_o();
    index_w_p();
    index_w_q();
    index_w_r();
    index_w_s();
    index_w_t();
    index_w_u();
    index_w_v();
    index_w_w();
    index_w_x();
    index_w_y();
    index_w_z();
}
            