import { index_d_a } from './index_d/index_d_a';
import { index_d_b } from './index_d/index_d_b';
import { index_d_c } from './index_d/index_d_c';
import { index_d_d } from './index_d/index_d_d';
import { index_d_e } from './index_d/index_d_e';
import { index_d_f } from './index_d/index_d_f';
import { index_d_g } from './index_d/index_d_g';
import { index_d_h } from './index_d/index_d_h';
import { index_d_i } from './index_d/index_d_i';
import { index_d_j } from './index_d/index_d_j';
import { index_d_k } from './index_d/index_d_k';
import { index_d_l } from './index_d/index_d_l';
import { index_d_m } from './index_d/index_d_m';
import { index_d_n } from './index_d/index_d_n';
import { index_d_o } from './index_d/index_d_o';
import { index_d_p } from './index_d/index_d_p';
import { index_d_q } from './index_d/index_d_q';
import { index_d_r } from './index_d/index_d_r';
import { index_d_s } from './index_d/index_d_s';
import { index_d_t } from './index_d/index_d_t';
import { index_d_u } from './index_d/index_d_u';
import { index_d_v } from './index_d/index_d_v';
import { index_d_w } from './index_d/index_d_w';
import { index_d_x } from './index_d/index_d_x';
import { index_d_y } from './index_d/index_d_y';
import { index_d_z } from './index_d/index_d_z';
export function index_d() {
    index_d_a();
    index_d_b();
    index_d_c();
    index_d_d();
    index_d_e();
    index_d_f();
    index_d_g();
    index_d_h();
    index_d_i();
    index_d_j();
    index_d_k();
    index_d_l();
    index_d_m();
    index_d_n();
    index_d_o();
    index_d_p();
    index_d_q();
    index_d_r();
    index_d_s();
    index_d_t();
    index_d_u();
    index_d_v();
    index_d_w();
    index_d_x();
    index_d_y();
    index_d_z();
}
            