import { index_i_a } from './src/index_i/index_i_a';
import { index_i_b } from './src/index_i/index_i_b';
import { index_i_c } from './src/index_i/index_i_c';
import { index_i_d } from './src/index_i/index_i_d';
import { index_i_e } from './src/index_i/index_i_e';
import { index_i_f } from './src/index_i/index_i_f';
import { index_i_g } from './src/index_i/index_i_g';
import { index_i_h } from './src/index_i/index_i_h';
import { index_i_i } from './src/index_i/index_i_i';
import { index_i_j } from './src/index_i/index_i_j';
import { index_i_k } from './src/index_i/index_i_k';
import { index_i_l } from './src/index_i/index_i_l';
import { index_i_m } from './src/index_i/index_i_m';
import { index_i_n } from './src/index_i/index_i_n';
import { index_i_o } from './src/index_i/index_i_o';
import { index_i_p } from './src/index_i/index_i_p';
import { index_i_q } from './src/index_i/index_i_q';
import { index_i_r } from './src/index_i/index_i_r';
import { index_i_s } from './src/index_i/index_i_s';
import { index_i_t } from './src/index_i/index_i_t';
import { index_i_u } from './src/index_i/index_i_u';
import { index_i_v } from './src/index_i/index_i_v';
import { index_i_w } from './src/index_i/index_i_w';
import { index_i_x } from './src/index_i/index_i_x';
import { index_i_y } from './src/index_i/index_i_y';
import { index_i_z } from './src/index_i/index_i_z';
export function index_i() {
    index_i_a();
    index_i_b();
    index_i_c();
    index_i_d();
    index_i_e();
    index_i_f();
    index_i_g();
    index_i_h();
    index_i_i();
    index_i_j();
    index_i_k();
    index_i_l();
    index_i_m();
    index_i_n();
    index_i_o();
    index_i_p();
    index_i_q();
    index_i_r();
    index_i_s();
    index_i_t();
    index_i_u();
    index_i_v();
    index_i_w();
    index_i_x();
    index_i_y();
    index_i_z();
}
            